services:
    # open-webui service for LLM interaction
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    env_file:
      - ../stack.env
    depends_on:
      - ollama
    ports:
      - "3001:8080"
    volumes:
      - ${OPENWEBUI_DATA}:/app/backend/data

  # ollama service for local LLMs
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: host
    ports:
      - "11434:11434"
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - ../stack.env
    volumes:
      - ${OLLAMA_DATA}:/root/.ollama
      - ${MODEL_LOCATION}:/mnt/Models
    restart: unless-stopped
    

