services:
    # open-webui service for LLM interaction
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    env_file:
      - ../stack.env
    depends_on:
      - ollama
    ports:
      - "3001:8080"
    volumes:
      - ${OPENWEBUI_DATA}:/app/backend/data

  # ollama service for local LLMs
  ollama-intel:
    image: dachack/ollama-intel-docker:latest
    container_name: ollama_intel
    ports:
      - "11434:11434"
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DEVICE=gpu
      - OLLAMA_NUM_GPU=999 # Forces all layers to offload to the iGPU
    volumes:
      - ${OLLAMA_DATA}:/root/.ollama
      - ${MODEL_LOCATION}:/mnt/Models
    restart: unless-stopped
    

